-- Automazioni tecniche del sistema Orione.
-- valid_from = 2026-01-15

CREATE OR REPLACE PROCEDURE PRC_ASSEGNA_TECNICO (
    P_INTERVENTO_ID IN NUMBER,
    P_TECNICO_ID IN NUMBER
) AS
BEGIN
    UPDATE INTERVENTO
       SET TECNICO_ID = P_TECNICO_ID,
           STATO = 'ASSEGNATO'
     WHERE ID = P_INTERVENTO_ID;
    CALL PRC_AUDIT_INTERVENTO(P_INTERVENTO_ID);
END;
/

CREATE OR REPLACE TRIGGER TRG_CHIUDI_INTERVENTO
BEFORE UPDATE OF STATO ON INTERVENTO
FOR EACH ROW
WHEN (NEW.STATO = 'PRONTO')
BEGIN
    UPDATE INTERVENTO
       SET STATO = 'CHIUSO',
           CHIUSO_IL = SYSDATE
     WHERE ID = :NEW.ID;
END;
/
