[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "dsl_mngr"
version = "0.1.0"
description = "DSL Manager v1."
requires-python = ">=3.12,<3.13"
dependencies = [
    "docling==2.97.0",
]

[project.scripts]
dsl-manager = "dsl_mngr.main:main"

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]
testpaths = ["tests"]
