-- Schema tecnico del sistema Orione Assistenza.
-- effective_from: 2026-01-15

CREATE TABLE TECNICO (
    ID NUMBER PRIMARY KEY,
    CODICE VARCHAR2(20) NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    LIVELLO NUMBER(1) NOT NULL,
    CONSTRAINT UQ_TECNICO_CODICE UNIQUE (CODICE)
);

CREATE TABLE ASSET (
    ID NUMBER PRIMARY KEY,
    MATRICOLA VARCHAR2(40) NOT NULL,
    DESCRIZIONE VARCHAR2(200),
    CRITICO CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT UQ_ASSET_MATRICOLA UNIQUE (MATRICOLA)
);

CREATE TABLE INTERVENTO (
    ID NUMBER PRIMARY KEY,
    ASSET_ID NUMBER NOT NULL,
    TECNICO_ID NUMBER,
    STATO VARCHAR2(30) DEFAULT 'APERTO' NOT NULL,
    PRIORITA VARCHAR2(10) NOT NULL,
    APERTO_IL DATE NOT NULL,
    CHIUSO_IL DATE,
    CONSTRAINT FK_INTERVENTO_ASSET FOREIGN KEY (ASSET_ID) REFERENCES ASSET(ID),
    CONSTRAINT FK_INTERVENTO_TECNICO FOREIGN KEY (TECNICO_ID) REFERENCES TECNICO(ID)
);

CREATE TABLE CHECKLIST (
    ID NUMBER PRIMARY KEY,
    INTERVENTO_ID NUMBER NOT NULL,
    CODICE VARCHAR2(30) NOT NULL,
    ESITO VARCHAR2(10),
    CONSTRAINT FK_CHECKLIST_INTERVENTO FOREIGN KEY (INTERVENTO_ID) REFERENCES INTERVENTO(ID)
);

CREATE INDEX IX_INTERVENTO_STATO ON INTERVENTO(STATO);
